# app/RAG/agents/report_agent.py

import os
import re
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

from app.services.logging_config import logger


class ReportGenerationAgent:
    def __init__(self, groq_api_key: str = None, output_dir: str = None):
        if output_dir is None:
            base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
            output_dir = os.path.join(base_dir, "generated_reports")
            
        self.output_dir = output_dir
        os.makedirs(self.output_dir, exist_ok=True)

    def _sanitize_utf8_text(self, text: str) -> str:
        """Removes characters that trigger Helvetica missing-glyph boxes or invalid ReportLab HTML tags."""
        # 1. Strip raw Base64 or code-block artifacts generated by the LLM
        text = re.sub(r'```(?:text|bash)?[\s\S]*?```', '', text)
        text = re.sub(r'JVBERi0x[\s\S]*', '', text)  # Strip raw PDF Base64 strings if present

        # 2. Fix ReportLab paraparser <br> syntax errors (Convert <br> or <br > to self-closing <br/>)
        text = re.sub(r'<br\s*/?>', '<br/>', text, flags=re.IGNORECASE)

        replacements = {
            "–": "-",
            "—": "-",
            "“": '"',
            "”": '"',
            "‘": "'",
            "’": "'",
            "½": "1/2",
            "¼": "1/4",
            "¾": "3/4",
            "…": "...",
            "\u00a0": " ",
            "\u25a0": "",
            "■": "-",
        }
        for bad_char, clean_char in replacements.items():
            text = text.replace(bad_char, clean_char)
        return text.strip()

    def convert_to_pdf(self, report_text: str, filename: str = "case_summary.pdf") -> str:
        pdf_path = os.path.join(self.output_dir, filename)
        
        # Initialize Document Template with Standard Margins
        doc = SimpleDocTemplate(
            pdf_path, 
            pagesize=letter, 
            rightMargin=36, 
            leftMargin=36, 
            topMargin=36, 
            bottomMargin=36,
            title="VetMind AI Report",
            author="VetMind AI"
        )
        
        styles = getSampleStyleSheet()
        
        # Color Palette
        PRIMARY_GREEN = colors.HexColor("#059669")
        HEADER_GREEN = colors.HexColor("#10B981")
        TEXT_DARK = colors.HexColor("#1F2937")
        
        # Styles Configuration
        title_style = ParagraphStyle(
            'PDFTitle', parent=styles['Heading1'], fontSize=16, leading=20, 
            textColor=PRIMARY_GREEN, spaceAfter=10, fontName='Helvetica-Bold'
        )
        h2_style = ParagraphStyle(
            'PDFH2', parent=styles['Heading2'], fontSize=11, leading=15, 
            textColor=PRIMARY_GREEN, spaceBefore=8, spaceAfter=4, fontName='Helvetica-Bold'
        )
        body_style = ParagraphStyle(
            'PDFBody', parent=styles['Normal'], fontSize=9, leading=13, 
            textColor=TEXT_DARK, spaceAfter=4
        )
        bullet_style = ParagraphStyle(
            'PDFBullet', parent=body_style, leftIndent=12, firstLineIndent=-8, spaceAfter=3
        )
        table_cell_style = ParagraphStyle(
            'TableCell', parent=styles['Normal'], fontSize=8, leading=11, 
            textColor=TEXT_DARK
        )
        table_header_style = ParagraphStyle(
            'TableHeader', parent=styles['Normal'], fontSize=8, leading=11, 
            fontName='Helvetica-Bold', textColor=colors.white
        )

        story = []
        
        # Document Header Banner
        story.append(Paragraph("VetMind AI — Clinical Case Summary Report", title_style))
        story.append(Spacer(1, 6))

        cleaned_text = self._sanitize_utf8_text(report_text)
        lines = cleaned_text.split('\n')
        
        table_buffer = []
        
        def flush_table_buffer(buffer, story_list):
            if not buffer:
                return
            
            table_data = []
            for row_idx, row_str in enumerate(buffer):
                cells = [c.strip() for c in row_str.split('|')[1:-1]]
                if not cells:
                    continue
                formatted_row = []
                for cell_text in cells:
                    cell_text = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', cell_text)
                    # Convert any <br> inside table cells to self-closing <br/>
                    cell_text = re.sub(r'<br\s*/?>', '<br/>', cell_text, flags=re.IGNORECASE)
                    
                    style = table_header_style if row_idx == 0 else table_cell_style
                    formatted_row.append(Paragraph(cell_text, style))
                table_data.append(formatted_row)
            
            if table_data:
                num_cols = max(len(row) for row in table_data)
                
                # Available printable width: 612 (letter width) - 72 (margins) = 540
                total_printable_width = 540
                
                # Proportional column sizing logic based on contents
                if num_cols == 2:
                    col_widths = [180, 360]
                elif num_cols == 3:
                    col_widths = [120, 220, 200]
                elif num_cols == 4:
                    col_widths = [80, 140, 180, 140]
                else:
                    col_widths = [total_printable_width / max(num_cols, 1)] * num_cols
                
                t = Table(table_data, colWidths=col_widths)
                t.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (-1, 0), HEADER_GREEN),
                    ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                    ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                    ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                    ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
                    ('TOPPADDING', (0, 0), (-1, -1), 4),
                    ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#D1D5DB")),
                    ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor("#F9FAFB")]),
                ]))
                story_list.append(Spacer(1, 4))
                story_list.append(t)
                story_list.append(Spacer(1, 6))

        for line in lines:
            clean_line = line.strip()
            
            # Detect Markdown tables
            if clean_line.startswith("|") and clean_line.endswith("|"):
                if "---" in clean_line or "|---" in clean_line:
                    continue
                table_buffer.append(clean_line)
                continue
            else:
                if table_buffer:
                    flush_table_buffer(table_buffer, story)
                    table_buffer = []

            if not clean_line or clean_line == "---":
                continue

            # Convert bold tags
            clean_line = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', clean_line)

            # Headers
            if clean_line.startswith("## ") or clean_line.startswith("### ") or (clean_line.endswith(":") and len(clean_line) < 45 and not clean_line.startswith("-")):
                heading_text = clean_line.replace("#", "").strip()
                story.append(Paragraph(heading_text, h2_style))
            # Bullet points and numbered items
            elif clean_line.startswith("-") or clean_line.startswith("*") or re.match(r'^\d+\.', clean_line):
                bullet_text = re.sub(r'^[-*\d.]+\s*', '', clean_line).strip()
                story.append(Paragraph(f"• {bullet_text}", bullet_style))
            # Standard body text
            else:
                story.append(Paragraph(clean_line, body_style))

        if table_buffer:
            flush_table_buffer(table_buffer, story)

        doc.build(story)
        logger.info(f"PDF compiled successfully at: {pdf_path}")
        return pdf_path